### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by hakan-demirli** [Mehmet-Emre-Dogan/cgpaGuesser#1]
It would be awesome if you could add a GUI.

**Comment by Mehmet-Emre-Dogan** [comment]
Thank you for your kind comment. I am planning to release the Manual Edition soon, and it will have a GUI.

**Comment by Mehmet-Emre-Dogan** [comment]
Please see the [link](https://github.com/Mehmet-Emre-Dogan/cgpaGuesser-Gui/releases/tag/v1.0). I have created a brand new repository and released the first stable version of the app.
